const sampleListings = [
    {
      title: "Cozy Beachfront Cottage",
      description: "Escape to this charming beachfront cottage for a relaxing getaway. Enjoy stunning ocean views and easy access to the beach.",
      image: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTB8fHRyYXZlbHxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      price: 1500,
      location: "Malibu",
      country: "United States",
    },
    {
      title: "Modern Loft in Downtown",
      description: "Stay in the heart of the city in this stylish loft with modern amenities.",
      image: "https://images.unsplash.com/photo-1550565115-6360db00a9f9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGxvZnR8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      price: 2000,
      location: "New York",
      country: "United States",
    },
    {
      title: "Rustic Mountain Cabin",
      description: "A peaceful retreat in the mountains. Perfect for nature lovers and adventure seekers.",
      image: "https://images.unsplash.com/photo-1521156226602-74b9c5be645a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTR8fGNhYmlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      price: 1200,
      location: "Aspen",
      country: "United States",
    },
    {
      title: "Charming Countryside Bungalow",
      description: "Relax in this charming bungalow surrounded by rolling hills and green pastures.",
      image: "https://images.unsplash.com/photo-1596886945952-4629bf1a7d41?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8OHx8YnVuZ2Fsb3d8ZW58MHx8MHx8fDA&auto=format&fit=crop&w=800&q=60",
      price: 1000,
      location: "Napa Valley",
      country: "United States",
    },
    {
      title: "Luxury Penthouse Suite",
      description: "Experience luxury living with panoramic city views from this high-rise penthouse.",
      image: "https://images.unsplash.com/photo-1586023492120-27b2c045efd9?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTZ8fHBldGhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      price: 5000,
      location: "Dubai",
      country: "United Arab Emirates",
    },
    {
      title: "Tropical Jungle Treehouse",
      description: "Reconnect with nature in this unique treehouse nestled in the heart of the jungle.",
      image: "https://images.unsplash.com/photo-1528150834755-5b7db89f039f?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8NHx8dHJlZWhvdXNlfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      price: 800,
      location: "Bali",
      country: "Indonesia",
    },
    {
      title: "Elegant Victorian House",
      description: "Step back in time with this elegant Victorian home, featuring antique decor and beautiful gardens.",
      image: "https://images.unsplash.com/photo-1617726846187-bca8d7fc95a4?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8dmVyaWN0b3JpYW4lMjBob3VzZXxlbnwwfHwwfHx8MA%3D%3D&auto=format&fit=crop&w=800&q=60",
      price: 2500,
      location: "London",
      country: "United Kingdom",
    },
    {
      title: "Scenic Lakeview Cabin",
      description: "Enjoy serene lake views from the comfort of this cozy cabin, perfect for a quiet retreat.",
      image: "https://images.unsplash.com/photo-1602501856451-7e724b44b4aa?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTh8fGNhYmlufGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      price: 1700,
      location: "Lake Tahoe",
      country: "United States",
    },
    {
      title: "Urban Studio Apartment",
      description: "A compact and modern studio apartment located in the heart of the city.",
      image: "https://images.unsplash.com/photo-1557804506-669a67965ba0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8c3R1ZGlvfGVufDB8fDB8fHww&auto=format&fit=crop&w=800&q=60",
      price: 900,
      location: "Tokyo",
      country: "Japan",
    },
    {
      title: "Mediterranean Villa",
      description: "A luxurious Mediterranean-style villa with breathtaking sea views and lush gardens.",
      image: "https://images.unsplash.com/photo-1570720695536-3eb705f2b580?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mnx8dmlsbGF8ZW58MHx8MHx8fDA%3D&auto=format&fit=crop&w=800&q=60",
      price: 3000,
      location: "Santorini",
      country: "Greece",
    },
  ];

  module.exports = {data : sampleListings};